version: "3.9"

# x-volumes: &service-volume
#   - type: bind
#     source: ./db
#     target: /db

x-web-app: &commun-web-app
  image: phx_solid
  depends_on:
    - db
  environment:
    - RELEASE_DISTRIBUTION=sname
  env_file:
    - .env-docker
  networks:
    - mynet

volumes:
  pg-data:

networks:
  mynet:

services:
  db:
    image: postgres:15.3-bullseye
    # environment:
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_DB=phx_solid_${MIX_ENV}
    #   - POSTGRES_USER=postgres
    env_file:
      - .env-docker
    restart: always
    networks:
      - mynet
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s

  livebook:
    image: ghcr.io/livebook-dev/livebook
    networks:
      - mynet
    depends_on:
      - db
    environment:
      # - MIX_ENV=prod
      - LIVEBOOK_DISTRIBUTION=sname
      - LIVEBOOK_COOKIE=supersecret
      - LIVEBOOK_PASSWORD=securesecret
      # - LIVEBOOK_NODE=livebook
      - SECRET_KEY_BASE=HRPM+KVxrXtYiIni27wn1pXrNc/cl7wjHl/u5TWQxqZkuvJ6Q4NBF+WMUVUpQVIY
    hostname: livebook
    volumes:
      - ./data:/data/
    ports:
      - "8080:8080"
      - "8081:8081"

  app0:
    <<: *commun-web-app
    hostname: app0
    ports:
      - "4000:4000"

  app1:
    <<: *commun-web-app
    hostname: app1
    ports:
      - "4001:4000"
  # app0:
  #   # build: .
  #   image: phx_solid
  #   # command: "start"
  #   hostname: app0
  #   depends_on:
  #     - db
  #   environment:
  #     RELEASE_DISTRIBUTION: sname
  #   #   RELEASE_NODE: "phx_solid@app0.mynet"
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env-docker
  #   networks:
  #     - mynet
  #   # volumes:
  #   #   - ./db:/db

  # app1:
  #   # build: .
  #   image: phx_solid
  #   # command: "start_iex"
  #   hostname: app1
  #   depends_on:
  #     - db
  #   environment:
  #     RELEASE_DISTRIBUTION: sname
  #   #   RELEASE_NODE: "phx_solid@app1.mynet"
  #   env_file:
  #     - .env-docker
  #   ports:
  #     - "4001:4000"
  #   networks:
  #     - mynet
  #   # volumes:
  #   #   - ./db:/db
